# Form implementation generated from reading ui file 'cartogram_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CartogramDialog(object):
    def setupUi(self, CartogramDialog):
        CartogramDialog.setObjectName("CartogramDialog")
        CartogramDialog.resize(640, 600)
        self.formLayout = QtWidgets.QFormLayout(CartogramDialog)
        self.formLayout.setObjectName("formLayout")
        self.messageBar = gui.QgsMessageBar(parent=CartogramDialog)
        self.messageBar.setObjectName("messageBar")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.messageBar
        )
        self.layerComboBoxLabel = QtWidgets.QLabel(parent=CartogramDialog)
        self.layerComboBoxLabel.setObjectName("layerComboBoxLabel")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.layerComboBoxLabel
        )
        self.layerComboBox = gui.QgsMapLayerComboBox(parent=CartogramDialog)
        self.layerComboBox.setObjectName("layerComboBox")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.layerComboBox
        )
        self.fieldListViewLabel = QtWidgets.QLabel(parent=CartogramDialog)
        self.fieldListViewLabel.setObjectName("fieldListViewLabel")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.fieldListViewLabel
        )
        self.fieldListView = QgsFieldListView(parent=CartogramDialog)
        self.fieldListView.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.SingleSelection
        )
        self.fieldListView.setObjectName("fieldListView")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.fieldListView
        )
        self.stopConditionsFrameLabel = QtWidgets.QLabel(parent=CartogramDialog)
        self.stopConditionsFrameLabel.setObjectName("stopConditionsFrameLabel")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.stopConditionsFrameLabel
        )
        self.stopConditionsFrame = QtWidgets.QFrame(parent=CartogramDialog)
        self.stopConditionsFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.stopConditionsFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.stopConditionsFrame.setObjectName("stopConditionsFrame")
        self.formLayout_2 = QtWidgets.QFormLayout(self.stopConditionsFrame)
        self.formLayout_2.setObjectName("formLayout_2")
        self.iterationsSpinBoxLabel = QtWidgets.QLabel(parent=self.stopConditionsFrame)
        self.iterationsSpinBoxLabel.setObjectName("iterationsSpinBoxLabel")
        self.formLayout_2.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.iterationsSpinBoxLabel
        )
        self.iterationsSpinBox = QtWidgets.QSpinBox(parent=self.stopConditionsFrame)
        self.iterationsSpinBox.setEnabled(True)
        self.iterationsSpinBox.setMinimum(1)
        self.iterationsSpinBox.setMaximum(9999)
        self.iterationsSpinBox.setProperty("value", 10)
        self.iterationsSpinBox.setObjectName("iterationsSpinBox")
        self.formLayout_2.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.iterationsSpinBox
        )
        self.averageErrorDoubleSpinBoxLabel = QtWidgets.QLabel(
            parent=self.stopConditionsFrame
        )
        self.averageErrorDoubleSpinBoxLabel.setObjectName(
            "averageErrorDoubleSpinBoxLabel"
        )
        self.formLayout_2.setWidget(
            2,
            QtWidgets.QFormLayout.ItemRole.LabelRole,
            self.averageErrorDoubleSpinBoxLabel,
        )
        self.averageErrorDoubleSpinBox = QtWidgets.QDoubleSpinBox(
            parent=self.stopConditionsFrame
        )
        self.averageErrorDoubleSpinBox.setSingleStep(0.5)
        self.averageErrorDoubleSpinBox.setProperty("value", 10.0)
        self.averageErrorDoubleSpinBox.setObjectName("averageErrorDoubleSpinBox")
        self.formLayout_2.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.averageErrorDoubleSpinBox
        )
        self.conditionsExplanationLabel = QtWidgets.QLabel(
            parent=self.stopConditionsFrame
        )
        self.conditionsExplanationLabel.setWordWrap(True)
        self.conditionsExplanationLabel.setObjectName("conditionsExplanationLabel")
        self.formLayout_2.setWidget(
            0,
            QtWidgets.QFormLayout.ItemRole.SpanningRole,
            self.conditionsExplanationLabel,
        )
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.stopConditionsFrame
        )
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=CartogramDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel
            | QtWidgets.QDialogButtonBox.StandardButton.Ok
        )
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(
            4, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.buttonBox
        )

        self.retranslateUi(CartogramDialog)
        self.buttonBox.accepted.connect(CartogramDialog.accept)  # type: ignore
        self.buttonBox.rejected.connect(CartogramDialog.reject)  # type: ignore
        self.layerComboBox.layerChanged["QgsMapLayer*"].connect(self.fieldListView.setLayer)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(CartogramDialog)

    def retranslateUi(self, CartogramDialog):
        _translate = QtCore.QCoreApplication.translate
        CartogramDialog.setWindowTitle(_translate("CartogramDialog", "cartogram3"))
        self.layerComboBoxLabel.setText(_translate("CartogramDialog", "Input layer:"))
        self.fieldListViewLabel.setToolTip(
            _translate(
                "CartogramDialog",
                "To compute cartograms for multiple fields, please use the Processing toolbox batch functionality.",
            )
        )
        self.fieldListViewLabel.setText(_translate("CartogramDialog", "Field:"))
        self.stopConditionsFrameLabel.setText(
            _translate("CartogramDialog", "Stop conditions:")
        )
        self.iterationsSpinBoxLabel.setText(
            _translate("CartogramDialog", "max. number of iterations:")
        )
        self.averageErrorDoubleSpinBoxLabel.setText(
            _translate("CartogramDialog", "max. average error:")
        )
        self.averageErrorDoubleSpinBox.setSuffix(_translate("CartogramDialog", "%"))
        self.conditionsExplanationLabel.setText(
            _translate(
                "CartogramDialog", "Calculation stops as soon as one condition is met."
            )
        )


from qgis import gui
from cartogram3.ui.qgsfieldlistview import QgsFieldListView
